### ISSUE TITLE
Is SQS 'RequestTemplates' not supported by this plugin?

### ISSUE THREAD

**Issue by iDVB** [serverless-operations/serverless-apigateway-service-proxy#66] opened 2020-02-10 15:38 UTC
I seems like APIG supports it but not the plugin.
```yaml
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: |
            Action=SendMessage&MessageBody=$input.body
```

**Comment by horike37** [comment] 2020-02-27 04:32
Yes, SQS `RequestTemplates` is hardcoded. To support for customizing that, it will need to fix here.
https://github.com/serverless-operations/serverless-apigateway-service-proxy/blob/master/lib/package/sqs/compileMethodsToSqs.js#L68

**Comment by horike37** [comment] 2020-02-27 04:45
closing once because of duplicate of #62

**Closed by horike37** 2020-02-27 04:45 UTC
Labels: enhancement, good first issue, help wanted
